# Generated by Django 5.0.7 on 2024-07-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_radnik'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TitanicSurvivalPredictions',
            new_name='TitanicSurvivalPrediction',
        ),
    ]
